version: 2
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - whitespace
    - err113
    - errorlint
    - nilerr
    - gocritic
    - nakedret
    - unconvert
    - dogsled
    - copyloopvar
    - prealloc
    - gosec
    - exhaustive
    - noctx
    - nolintlint
    - promlinter
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - noctx
      - text: "var-naming.*avoid package names"
        linters:
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0